### ISSUE TITLE
TODO: 规范化笔记中的内容

### ISSUE THREAD

**Issue by x2rs** [x2rs/x2rs.github.io#19]
有些笔记是AI生成，有些直接照搬链接，有些直接拿b站视频截图，缺少自己的思考，时间久了自己都会困惑。

TODO：列一个需要规范化的笔记的清单。

**Comment by x2rs** [comment]
以下笔记的内容需要规范化：
- [ ] [Cramér-Rao不等式](https://x2rs.github.io/notes/Cramer-Rao/)为AI生成
- [ ] [析构顺序](https://x2rs.github.io/notes/order-of-destructor-calls/)直接引用链接
- [ ] [强符号和弱符号](https://x2rs.github.io/notes/strong-and-weak-symbol/)为AI生成
- [ ] [C++ 继承访问说明符](https://x2rs.github.io/notes/cpp-derived-class-access/)过于简陋
